# Dockerfile para Node.js
FROM node:22

# Criar diretório de trabalho
WORKDIR /app

# Copiar arquivos da aplicação (se necessário)
COPY . .

# Instalar dependências
RUN npm install

# Expor a porta padrão da aplicação
EXPOSE 3000

# Comando padrão
CMD ["npm", "start"]